env: "local" # local, dev, prod
storage_path: "./storage.db"
migrations_path: "./assets/migrations/sqlite/"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s # Время жизни соединения с клиентом


