env: "local" # local, dev, prod
storage_path: "./storage.db"
alias_length: 6
goose:
  print_status: false
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s # Время жизни соединения с клиентом
  user: "myuser"
  password: "mypass"


