env: "prod" # local, dev, prod
storage_path: "./storage.db"
alias_length: 6
goose:
  print_status: false
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s # Время жизни соединения с клиентом
  user: "babenoff"


